name: riocaja_smart
description: "RíoCaja Smart - Gestión de comprobantes CNB"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:        # NUEVO - Para soporte de idiomas
    sdk: flutter
  camera: ^0.10.5+8           # Para acceso a la cámara
  firebase_core: ^2.24.2      # Base de Firebase
  google_mlkit_text_recognition: ^0.11.0  # Para reconocimiento de texto
  google_mlkit_commons: ^0.6.0  # Dependencia de MLKit
  http: ^1.1.0                # Para llamadas API
  provider: ^6.1.1            # Para gestión de estado
  shared_preferences: ^2.2.2  # Para almacenamiento local
  path_provider: ^2.1.1       # Para acceso a directorios
  pdf: ^3.10.1                # Para generar PDF
  intl: 0.19.0               # Para formateo de fechas y números
  excel: ^4.0.1              # Para crear archivos Excel
  share_plus: ^7.2.1         # Para compartir archivos

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  generate: true                # NUEVO - Para generar localizaciones
  assets:
    - assets/images/          # Carpeta de imágenes
    - assets/app_icon.png     # Ícono de la aplicación

# Configuración del ícono de la aplicación
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/app_icon.png"
    background_color: "#2E7D32"
    theme_color: "#2E7D32"
  windows:
    generate: true
    image_path: "assets/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/app_icon.png"