// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvhkHheWlOCUUsSP7_G8cdQ5cEzxWAK5A',
    appId: '1:592507291957:web:your_web_app_id',
    messagingSenderId: '592507291957',
    projectId: 'riocaja-smart',
    authDomain: 'riocaja-smart.firebaseapp.com',
    storageBucket: 'riocaja-smart.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvhkHheWlOCUUsSP7_G8cdQ5cEzxWAK5A',
    appId: '1:592507291957:android:eab0929814e67512fb247c',
    messagingSenderId: '592507291957',
    projectId: 'riocaja-smart',
    storageBucket: 'riocaja-smart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVbBnst8Y0soCCMZF3hWHIVvB6wCHV3io',
    appId: '1:592507291957:ios:103bd6e453d4e71efb247c',
    messagingSenderId: '592507291957',
    projectId: 'riocaja-smart',
    storageBucket: 'riocaja-smart.firebasestorage.app',
    iosBundleId: 'com.example.riocajaSmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVbBnst8Y0soCCMZF3hWHIVvB6wCHV3io',
    appId: '1:592507291957:ios:103bd6e453d4e71efb247c',
    messagingSenderId: '592507291957',
    projectId: 'riocaja-smart',
    storageBucket: 'riocaja-smart.firebasestorage.app',
    iosBundleId: 'com.example.riocajaSmart',
  );
}